/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as WritingsIndexRouteImport } from './routes/writings/index'
import { Route as WritingsSlugRouteImport } from './routes/writings/$slug'
import { Route as ApiChatIndexRouteImport } from './routes/api/chat/index'
import { Route as ApiChatFollowUpsRouteImport } from './routes/api/chat/follow-ups'
import { Route as ProjectsPcoboosterDemoRouteImport } from './routes/projects/pcobooster/demo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingsIndexRoute = WritingsIndexRouteImport.update({
  id: '/writings/',
  path: '/writings/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingsSlugRoute = WritingsSlugRouteImport.update({
  id: '/writings/$slug',
  path: '/writings/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatIndexRoute = ApiChatIndexRouteImport.update({
  id: '/api/chat/',
  path: '/api/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatFollowUpsRoute = ApiChatFollowUpsRouteImport.update({
  id: '/api/chat/follow-ups',
  path: '/api/chat/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsPcoboosterDemoRoute = ProjectsPcoboosterDemoRouteImport.update({
  id: '/projects/pcobooster/demo',
  path: '/projects/pcobooster/demo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/quotes': typeof QuotesRoute
  '/timeline': typeof TimelineRoute
  '/writings/$slug': typeof WritingsSlugRoute
  '/projects/': typeof ProjectsIndexRoute
  '/writings/': typeof WritingsIndexRoute
  '/api/chat/follow-ups': typeof ApiChatFollowUpsRoute
  '/projects/pcobooster/demo': typeof ProjectsPcoboosterDemoRoute
  '/api/chat/': typeof ApiChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/quotes': typeof QuotesRoute
  '/timeline': typeof TimelineRoute
  '/writings/$slug': typeof WritingsSlugRoute
  '/projects': typeof ProjectsIndexRoute
  '/writings': typeof WritingsIndexRoute
  '/api/chat/follow-ups': typeof ApiChatFollowUpsRoute
  '/projects/pcobooster/demo': typeof ProjectsPcoboosterDemoRoute
  '/api/chat': typeof ApiChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/quotes': typeof QuotesRoute
  '/timeline': typeof TimelineRoute
  '/writings/$slug': typeof WritingsSlugRoute
  '/projects/': typeof ProjectsIndexRoute
  '/writings/': typeof WritingsIndexRoute
  '/api/chat/follow-ups': typeof ApiChatFollowUpsRoute
  '/projects/pcobooster/demo': typeof ProjectsPcoboosterDemoRoute
  '/api/chat/': typeof ApiChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/contact'
    | '/quotes'
    | '/timeline'
    | '/writings/$slug'
    | '/projects/'
    | '/writings/'
    | '/api/chat/follow-ups'
    | '/projects/pcobooster/demo'
    | '/api/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/contact'
    | '/quotes'
    | '/timeline'
    | '/writings/$slug'
    | '/projects'
    | '/writings'
    | '/api/chat/follow-ups'
    | '/projects/pcobooster/demo'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/contact'
    | '/quotes'
    | '/timeline'
    | '/writings/$slug'
    | '/projects/'
    | '/writings/'
    | '/api/chat/follow-ups'
    | '/projects/pcobooster/demo'
    | '/api/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  ContactRoute: typeof ContactRoute
  QuotesRoute: typeof QuotesRoute
  TimelineRoute: typeof TimelineRoute
  WritingsSlugRoute: typeof WritingsSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  WritingsIndexRoute: typeof WritingsIndexRoute
  ApiChatFollowUpsRoute: typeof ApiChatFollowUpsRoute
  ProjectsPcoboosterDemoRoute: typeof ProjectsPcoboosterDemoRoute
  ApiChatIndexRoute: typeof ApiChatIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writings/': {
      id: '/writings/'
      path: '/writings'
      fullPath: '/writings/'
      preLoaderRoute: typeof WritingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writings/$slug': {
      id: '/writings/$slug'
      path: '/writings/$slug'
      fullPath: '/writings/$slug'
      preLoaderRoute: typeof WritingsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/': {
      id: '/api/chat/'
      path: '/api/chat'
      fullPath: '/api/chat/'
      preLoaderRoute: typeof ApiChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/follow-ups': {
      id: '/api/chat/follow-ups'
      path: '/api/chat/follow-ups'
      fullPath: '/api/chat/follow-ups'
      preLoaderRoute: typeof ApiChatFollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/pcobooster/demo': {
      id: '/projects/pcobooster/demo'
      path: '/projects/pcobooster/demo'
      fullPath: '/projects/pcobooster/demo'
      preLoaderRoute: typeof ProjectsPcoboosterDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  ContactRoute: ContactRoute,
  QuotesRoute: QuotesRoute,
  TimelineRoute: TimelineRoute,
  WritingsSlugRoute: WritingsSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  WritingsIndexRoute: WritingsIndexRoute,
  ApiChatFollowUpsRoute: ApiChatFollowUpsRoute,
  ProjectsPcoboosterDemoRoute: ProjectsPcoboosterDemoRoute,
  ApiChatIndexRoute: ApiChatIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
